# Copyright (c) 2018. Deutsches Zentrum fuer Luft- und Raumfahrt (DLR).
# All rights reserved.  http://www.dlr.de/sl

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/

import datetime
from abc import abstractmethod
from pathlib import Path

import numpy as np
import pandas as pd

from sosid.simulation.simulation import SimulationParameters
from sosid.util.abc import ABCMeta


class BaseDoEGenerator(metaclass=ABCMeta):
    """Contains useful methods for doe generation and validation.

    Note: Extends `DoEPy` methods
    """

    def __init__(
        self,
        default_parameters,
        doe_parameters,
        project_name,
    ):
        self.parameters: SimulationParameters = default_parameters
        self.doe_parameters: dict = doe_parameters
        self.project_name: str = project_name
        self.validate_usecase_params(doe_parameters, default_parameters)

    def build_full_fact(self, factor_level_ranges):
        """Builds a full factorial design dataframe from a dictionary of
        factor/level ranges.
        Example of the dictionary which is needed as the input:
        {'Pressure':[50,60,70],
        'Temperature':[290, 320, 350],
        'Flow rate':[0.9,1.0]}
        """
        factor_lvl_count = []
        factor_lists = []

        for key in factor_level_ranges:
            factor_lvl_count.append(len(factor_level_ranges[key]))
            factor_lists.append(factor_level_ranges[key])

        x = self.fullfact_corrected(factor_lvl_count)
        df = self.construct_df(x, factor_lists)
        df.columns = factor_level_ranges.keys()

        return df

    def fullfact_corrected(self, levels):
        """Create a general full-factorial design

        Args:
            levels (list): An array of integers that indicate the
            number of levels of each input design factor.

        Returns:
            mat (2d-array): The design matrix with coded levels 0 to k-1
            for a k-level factor

        Example:
            >>> fullfact([2, 4, 3])
            array([[ 0.,  0.,  0.],
                [ 1.,  0.,  0.],
                [ 0.,  1.,  0.],
                [ 1.,  1.,  0.],
                [ 0.,  2.,  0.],
                [ 1.,  2.,  0.],
                [ 0.,  3.,  0.],
                [ 1.,  3.,  0.],
                [ 0.,  0.,  1.],
                [ 1.,  0.,  1.],
                [ 0.,  1.,  1.],
                [ 1.,  1.,  1.],
                [ 0.,  2.,  1.],
                [ 1.,  2.,  1.],
                [ 0.,  3.,  1.],
                [ 1.,  3.,  1.],
                [ 0.,  0.,  2.],
                [ 1.,  0.,  2.],
                [ 0.,  1.,  2.],
                [ 1.,  1.,  2.],
                [ 0.,  2.,  2.],
                [ 1.,  2.,  2.],
                [ 0.,  3.,  2.],
                [ 1.,  3.,  2.]])
        """
        n = len(levels)  # number of factors
        nb_lines = np.prod(levels)  # number of trial conditions
        H = np.zeros((nb_lines, n))

        level_repeat = 1
        range_repeat = np.prod(levels)
        for i in range(n):
            range_repeat //= levels[i]
            lvl = []
            for j in range(levels[i]):
                lvl += [j] * level_repeat
            rng = lvl * range_repeat
            level_repeat *= levels[i]
            H[:, i] = rng

        return H

    def construct_df(self, x, r):
        """Function for constructing a DataFrame from a numpy array
        generated by PyDOE function and individual lists
        """
        # TODO find way to optimize dtype assignment - "object" type is
        # most storage intensive
        df = pd.DataFrame(data=x, dtype="object")
        for i in df.index:
            for j in range(len(list(df.iloc[i]))):
                df.iloc[i][j] = r[j][int(df.iloc[i][j])]
        return df

    def validate_usecase_params(self, doe_params, default_params):
        """Check each parameter in doe input against sim parameters.

        Args:
            usecase_params (dict): DoE usecase parameters to validate
            sim_parameters (SimulationParameters): Simulation Parameters
            class to validate against

        Raises:
            ValueError: If key in `usecase_params` not defined in
            `sim_parameters`
        """
        for key in doe_params:
            if key in default_params.__dict__:
                pass
            else:
                raise ValueError(
                    f"DoE input: {key} not in {default_params.__name__}"
                )

    def post_process_ac_inputs(self, doe, ac_parameters):
        """Merge aircraft inputs into single doe file in the form
        expected by `DesignOfExperiments`

        Args:
            doe (dict): DoE of Use Case
            ac_parameters (dict): Aircraft parameters for DoE
        """

        def make_dict(row, column_names):
            # Group agents' parameters by agent type
            agents_params = {
                i: [param[1] for param in list(column)]
                for i, column in groupby(
                    [column.split() for column in column_names], lambda x: x[0]
                )
            }

            return [
                {
                    "file_name": agent,
                    **{
                        param: row[" ".join([agent, param])]
                        for param in agents_params[agent]
                    },
                }
                for agent in agents_params
            ]

        agents_column = doe.apply(make_dict, axis=1, args=(ac_parameters,))
        doe["agents"] = agents_column
        doe.drop(columns=ac_parameters.keys(), inplace=True)
        return doe

    def doe_file_name(self, count):  # noqa D102
        date_time = datetime.datetime.now().strftime("%Y-%m-%d|%H-%M-%S")
        date_stamp, time_stamp = date_time.split("|")
        file_name = (
            date_stamp
            + self.project_name
            + time_stamp
            + "_"
            + str(count)
            + "points.json"
        )
        return file_name

    @abstractmethod
    def generate_doe(self):
        pass


class FullFactDoEGenerator(BaseDoEGenerator):
    """Generates and returns Full Factorial Design of Experiments.

    Usage: All doe parameters except for aircraft definition and
    distribution are passed as dict to `usecase_params`. Each entry in
    the list represents one value of the variable.

    validation_parameters: Instance of `SimulationParameters` like class
        used for validation of the doe parameters

    usecase_params: Dict containing doe parameters where key should
        match input in ``validation_parameters`` and each entry in its
        value must follow input rules of its corressponding definition
        in `validation_parameters`

    usecase_params = {
        "spam": [40, 55, 70],
        "foo": [0.2, 0.4],
        "eggs": ["el", "two"],
        "ham": [(1, 1, 1), (2, 2, 2)],
    }

    aircraft_doe: aircraft definition file is defined as key and its
        distribution across the bases are represented by the tuple. Each
        Tuple represents one design point. Each entry in the tuple
        represents how many of the aircraft defined by key are in the
        base correspondig to that entry. The length of the tuples must
        match number of bases.

    aircraft_doe = {
        "ac_1.json": [(1, 0, 0, 0), (1, 1, 0, 0), (1, 1, 1, 0)],
        "ac_2.json": [(1, 0, 0, 0), (1, 1, 0, 0), (1, 1, 1, 0)],
    }

    Where multiple aircraft are defined, a heterogenous fleet is
    generated using a full factorial DoE.

    project_name: Used as part of generated doe file name
    data_directory: Location to save generated doe file
    """

    def __init__(
        self,
        default_parameters,
        doe_params,
        project_name,
        data_directory,
    ):
        super().__init__(default_parameters, doe_params, project_name)
        doe = self.generate_doe(doe_params)
        self.filename = self.doe_file_name(len(doe))
        full_path = str(
            Path(data_directory.parent / "gen_output" / self.filename)
        )
        doe.to_json(full_path, orient="index", indent=4)
        print(f"Generated DoE file name: {self.filename}")

    def generate_doe(self, doe_inputs):  # noqa D102
        return self.build_full_fact(doe_inputs)
