# Copyright (c) 2018. Deutsches Zentrum fuer Luft- und Raumfahrt (DLR).
# All rights reserved.  http://www.dlr.de/sl

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/

"""Configuration file for the Sphinx documentation builder.

This file does only contain a selection of the most common options.
For a full list see the documentation:

http://www.sphinx-doc.org/en/master/config
"""

import os
import sys

import sphinx_bootstrap_theme
from pkg_resources import get_distribution

# -- Path setup ---------------------------------------------------------# noqa

# If extensions (or modules to document with autodoc) are in another
# directory, add these directories.rst to sys.path here. If the
# directory is relative to the documentation root, use os.path.abspath
# to make it absolute, like shown.

# Forces Sphinx to look 2 directories.rst up to find all modules
sys.path.insert(0, os.path.abspath("../.."))
sys.path.insert(1, os.path.abspath("../../src"))

# TODO rename _static folder into static for uniformity

# -- Project information ------------------------------------------------# noqa

project = "SoSID Toolkit"
copyright = "2019, DLR Institute of System Architectures in Aeronautics"
author = "San Kilkis"

# Getting Current version and ensuring X.Y format
version = ".".join(get_distribution("sosid").version.split(".")[:2])
# The full version, including alpha/beta/rc tags
# release = u'2.0'


# -- General configuration ----------------------------------------------# noqa

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = "2.2.0"

# If your documentation needs a minimal version of Sphinx extensions,
# state it here needs_extensions = {'sphinxcontrib.bibtex': '0.4.1'} #
# Currently does not work, added to documentation read-me instead

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "docs.ext.numba_patch",  # Exposes CUDA device funcs to Sphinx
    "sphinx.ext.todo",
    "sphinx.ext.mathjax",
    "sphinx.ext.ifconfig",
    "sphinx.ext.viewcode",
    "sphinx.ext.githubpages",
    "sphinx.ext.graphviz",
    "sphinx.ext.inheritance_diagram",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx_autodoc_typehints",  # Must be loaded after Napoleon
    "sphinxcontrib.bibtex",
    "sphinxcontrib.plantuml",
]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:

# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to
# documentation for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories.rst to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = [
    "doc_build",
    "Thumbs.db",
    ".DS_Store",
    "_static/rst/coloredtext.rst",
    "wing/airfoil.rst",
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# -- Extension configuration --------------------------------------------# noqa

# Links to external projects directories containing objects.inv files.
intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "numpy": ("https://docs.scipy.org/doc/numpy", None),
    "numba": ("https://numba.pydata.org/numba-doc/latest/", None),
    "PIL": ("https://pillow.readthedocs.io/en/stable/", None),
}
# Use the command to find available intersphinx references in
# objects.inv python -m sphinx.ext.intersphinx URL/objects.inv

# Overwriting Autodoc Defaults
autodoc_default_options = {"member-order": "bysource"}

# If true, `todo` and `todoList` produce output
todo_include_todos = False

# Napoleon settings
napoleon_google_docstring = True
napoleon_numpy_docstring = False  # Enforcing Google docstring format
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_keyword = True
napoleon_use_rtype = True

# Plant UML Settings
# TODO try out using os.env('') to see if plantuml is in the path
plantuml_path = os.path.join("..", "plantuml", "lib", "plantuml.jar")
# IMPORTANT The double quotations around the path are necessary
plantuml = f'java -jar "{os.path.abspath(plantuml_path)}"'
plantuml_output_format = "svg_img"


# -- Customization ------------------------------------------------------# noqa

# Colored/Formatted Text
# rst_prolog = open('_static/rst/coloredtext.rst', 'r').read()

# Numbered Figures
numfig = True
numfig_format = {
    "figure": "Figure %s",
    "table": "Table %s",
    "code-block": "Listing %s",
    "section": "Section %s",
}

# Numbered Equations
math_numfig = True
math_eqref_format = "Equation {number}"

# Module Names Infront of Members
add_module_names = False

# Show Author Names for codeauthor and sectionauthor directives
show_author = True


# -- Options for HTML output --------------------------------------------# noqa

# The theme to use for HTML and HTML Help pages.
# See the documentation for a list of builtin themes.

html_theme = "bootstrap"

# Icon source: https://www.flaticon.com/free-icon/filter_221770
html_logo = "_static/assets/filter.svg"
# Potential other icons:
# https://www.flaticon.com/free-icon/screening_2082221

# Add any paths that contain custom themes here, relative to this
# directory. ``get_html_theme_path`` returns a list, so you can
# concatenate with any other theme directories you would like.
html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()

# Output file base name for HTML help builder.
htmlhelp_basename = "SoSIDDoc"

# Add any paths that contain custom static files (such as style sheets)
# here, relative to this directory. They are copied after the builtin
# static files, so a file named "default.css" will overwrite the builtin
# "default.css".
html_static_path = ["_static"]

# Theme options are theme-specific and customize the look and feel of a
# theme further.  For a list of options available for each theme, see
# the documentation.
html_theme_options = {
    # Navigation bar title. (Default: ``project`` value)
    "navbar_title": project,
    # Tab name for entire site. (Default: "Site")
    "navbar_site_name": "Site",
    # Tab name for the current pages TOC. (Default: "Page")
    "navbar_pagenav_name": "Contents",
    # A list of tuples containing pages or urls to link to.
    # Valid tuples should be in the following forms:
    #    (name, page)  # a link to a page
    #    (name, "/aa/bb", 1)  # a link to an arbitrary relative url
    #    (name, "http://example.com", True) # arbitrary absolute url
    # Note the "1" or "True" value above as the third argument indicates
    # an arbitrary url.
    # "navbar_links": [
    #     ("Examples", "examples"),
    #     ("Link", "http://example.com", True),
    # ],
    # Global TOC depth for "site" navbar tab. (Default: 1)
    # Switching to -1 shows all levels.
    "globaltoc_depth": 2,
    # Include hidden TOCs in Site navbar?
    #
    # Note: If this is "false", you cannot have mixed ``:hidden:`` and
    # non-hidden ``toctree`` directives in the same page, or else the
    # build will break.
    #
    # Values: "true" (default) or "false"
    "globaltoc_includehidden": "true",
    # HTML navbar class (Default: "navbar") to attach to <div> element.
    # For black navbar, do "navbar navbar-inverse"
    "navbar_class": "navbar",
    # Fix navigation bar to top of page?
    # Values: "true" (default) or "false"
    "navbar_fixed_top": "true",
    # Location of link to source.
    # Options are "nav" (default), "footer" or anything else to exclude.
    "source_link_position": "footer",
    # Bootswatch (http://bootswatch.com/) theme.
    #
    # Options are nothing (default) or the name of a valid theme such
    # such as "cosmo" or "sandstone".
    #
    # Example themes:
    # * flatly
    # * sandstone (v3 only)
    # * united
    # * yeti (v3 only)
    "bootswatch_theme": "paper",
    # Choose Bootstrap version.
    # Values: "3" (default) or "2" (in quotes)
    "bootstrap_version": "3",
}

# This is necessary to fix a bug in the sphinx-rtd theme that would
# over-ride user specified widths
html_context = {
    "css_files": [
        "_static/css/theme_overrides.css",
        # '_static/css/slideshow.css'],
    ]
}

# Custom sidebar templates, must be a dictionary that maps document
# names to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

# -- Options for HTMLHelp output ----------------------------------------# noqa

# Output file base name for HTML help builder.
htmlhelp_basename = "SoSID Toolkit"

# -- Custom Set-up Actions ----------------------------------------------# noqa


# Allows use of slide-shows for images using JavaScript
# def setup(app):
#     app.add_javascript('js/slideshow.js')
