# Copyright (c) 2018. Deutsches Zentrum fuer Luft- und Raumfahrt (DLR).
# All rights reserved.  http://www.dlr.de/sl

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/

"""Parsers for testing output of Sphinx builds.

This module contains all parser classes to retrieve information from
Sphinx builds for testing purposes
"""

from html.parser import HTMLParser


class HTMLElement:
    """Dataclass describing an HTML Element <div class = "box">.

    Args:
        tag: HTML tag (i.e. div from the example above)
        html_class: HTML class (i.e box from the example above)

    """

    # Decreases memory consumption by making the class immutable
    __slots__ = ["as_attrs", "html_class", "tag"]

    def __init__(self, tag: str, html_class: str):
        self.tag = tag
        self.html_class = html_class
        self.as_attrs = [("class", html_class)]

    def match(
        self, tag: str, attrs: list[tuple[int, int]] | None = None
    ) -> bool:
        """Returns True if ``tag`` and ``attrs`` match object attrs.

        Once an HTMLElement is defined, this method should be used to
        check for match cases::

            BOX_ELEMENT = HTMLElement(tag="div", html_class="function")

        """
        if attrs is not None:
            return tag == self.tag and self.as_attrs == attrs
        return tag == self.tag


#: HTML element that Sphinx creates for functions
FUNCTION_ELEMENT = HTMLElement(tag="dl", html_class="py function")

#: HTML element Sphinx creates for function names
NAME_ELEMENT = HTMLElement(tag="span", html_class="sig-name descname")


class SphinxFunctionNameExtractor(HTMLParser):
    """Gets Sphinx autogenerated function names from an HTML file."""

    #: Output of HTML Parsing (List of functions  in the HTML doc)
    extracted_data = set()

    #: Is the parser currently within a function block?
    inside_function = False

    #: Is the parser currently within the function name block?
    inside_name = False

    def handle_starttag(self, tag, attrs):
        """Executed when entering a tag."""
        if FUNCTION_ELEMENT.match(tag, attrs):
            self.inside_function = True
        elif NAME_ELEMENT.match(tag, attrs):
            self.inside_name = True

    def handle_endtag(self, tag):
        """Executed when leaving a tag."""
        if FUNCTION_ELEMENT.match(tag):
            self.inside_function = False
        elif NAME_ELEMENT.match(tag):
            self.inside_name = False

    def handle_data(self, data):
        """Executed when processing data within a tag."""
        if self.inside_function and self.inside_name:
            self.extracted_data.add(data)

    def find_functions(self, html_str: str) -> set[str]:
        """Finds all functions within a Sphinx HTML file."""
        self.feed(html_str)
        return self.extracted_data
